apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt
  commonName: "web-sample.k8sutils.com"
  dnsNames:
    - "web-sample.k8sutils.com"

